### ISSUE TITLE
water wave

### ISSUE THREAD

**Issue by kerolloz** [empw-org/front-end#3]
![image](https://user-images.githubusercontent.com/36763164/75590024-0c326180-5a85-11ea-8748-9b5e86979c4a.png)

**Comment by kerolloz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Solve Landing Page issues](https://trello.com/c/B7Cl4Z7C/6-solve-landing-page-issues)

**Comment by AlaaOthman98** [comment]
Done.
